version: "3.3"
services:

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./sql_init/resource_manage.sql:/docker-entrypoint-initdb.d/resource_manage.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  backend:
    user: "${UID}:${GID}"
    container_name: wjgl
    build:
      context: .
      dockerfile: dockerfiles/backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./wjgl-master:/opt/wjgl-master
    environment:
      - PYTHONPATH=/opt/wjgl-master
      - DJANGO_SETTINGS_MODULE=wjgl.settings

