# Generated by Django 2.2.3 on 2022-08-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_auto_20191106_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='remark',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='文件备注'),
        ),
        migrations.AlterField(
            model_name='approvelog',
            name='isapprove',
            field=models.CharField(choices=[('1', '已审批'), ('2', '已驳回')], max_length=1, verbose_name='终审'),
        ),
        migrations.AlterField(
            model_name='file',
            name='isapprove',
            field=models.CharField(choices=[('0', '未审批'), ('1', '已审批'), ('2', '已驳回')], default='0', max_length=1, verbose_name='终审'),
        ),
    ]
