# Generated by Django 2.2.3 on 2022-08-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_auto_20220812_1507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApproveLog',
        ),
        migrations.DeleteModel(
            name='PublicIp',
        ),
    ]
